# Generated by Django 5.2.12 on 2026-03-26 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(max_length=128)),
                ('album', models.CharField(max_length=128)),
                ('other', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('band', models.CharField(max_length=128)),
                ('album', models.CharField(max_length=128)),
                ('other', models.CharField(max_length=512)),
                ('cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.cd')),
            ],
        ),
    ]
