# Generated by Django 5.2.12 on 2026-03-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(max_length=128)),
                ('album', models.CharField(max_length=128)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('band', 'album'), name='Duplilcate cd')],
            },
        ),
    ]
