# Generated by Django 5.2.12 on 2026-03-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd',
            name='other',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='other',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
