# Generated by Django 5.2.12 on 2026-03-26 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_cd_other_alter_song_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cd',
            name='other',
        ),
        migrations.RemoveField(
            model_name='song',
            name='other',
        ),
    ]
