# Generated by Django 5.2.12 on 2026-03-27 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_cd_other_remove_song_other'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
